codecov:
  require_ci_to_pass: true
ignore:
  - "**/ValidationTest"
  - "**/ValidationTestDestination"
coverage:
  status:
    project:
      mirth-channel-code:
        target: auto
        threshold: 1%
        flags:
          - mirth-channel-code

    patch:
      mirth-channel-code:
        target: 80
        threshold: 1%
        base: auto
        flags:
          - mirth-channel-code

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
  show_carryforward_flags: false

flags:
  mirth-channel-code:
    paths:
      - mirth-channel-code/
    carryforward: true
