[libraries]
guava = "com.google.guava:guava:31.1-jre"

interop-common = "com.projectronin.interop:interop-common:3.6.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.6.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.6.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.6.0"

interop-fhir = "com.projectronin.interop.fhir:interop-fhir:7.8.1"
interop-fhir-generators = "com.projectronin.interop.fhir:interop-fhir-generators:7.8.1"

interop-ehr-api = "com.projectronin.interop.ehr:interop-ehr:9.9.0"
interop-ehr-cerner = "com.projectronin.interop.ehr:interop-ehr-cerner:9.9.0"
interop-ehr-epic = "com.projectronin.interop.ehr:interop-ehr-epic:9.9.0"
interop-ehr-fhir-ronin = "com.projectronin.interop.ehr:interop-fhir-ronin:9.9.0"
interop-ehr-liquibase = "com.projectronin.interop.ehr:interop-ehr-liquibase:9.9.0"
interop-ehr-tenant = "com.projectronin.interop.ehr:interop-tenant:9.9.0"

interop-publishers-aidbox = "com.projectronin.interop.publish:interop-aidbox:7.7.0"
interop-publishers-datalake = "com.projectronin.interop.publish:interop-datalake:7.7.0"
interop-publishers-core = "com.projectronin.interop.publish:interop-publishers:7.7.0"
interop-publishers-kafka = "com.projectronin.interop.publish:interop-kafka:7.7.0"

interop-queue-api = "com.projectronin.interop.queue:interop-queue:1.6.1"
interop-queue-db = "com.projectronin.interop.queue:interop-queue-db:1.6.1"
interop-queue-kafka = "com.projectronin.interop.queue:interop-queue-kafka:1.6.1"
interop-queue-liquibase = "com.projectronin.interop.queue:interop-queue-liquibase:1.6.1"

interop-validation-client = "com.projectronin.interop.validation:interop-validation-client:2.0.0"
interop-kafka-event-resource-publish = "com.projectronin.contract.event:event-interop-resource-publish:1.0.1"
interop-kafka-event-resource-load = "com.projectronin.contract.event:event-interop-resource-load:1.0.0"
interop-kafka-event-resource-request = "com.projectronin.contract.event:event-interop-resource-request:1.0.0"


jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.15.0"
jackson-core = "com.fasterxml.jackson.core:jackson-core:2.15.0"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.15.0"
jackson-dataformat-xml = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.15.0"
jackson-dataformat-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.0"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.0"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.15.0"

jakarta-ws = "jakarta.ws.rs:jakarta.ws.rs-api:2.1.2"
jersey-glassfish-client = "org.glassfish.jersey.core:jersey-client:2.35"
kafka-clients = "org.apache.kafka:kafka-clients:3.4.0"
kotlin-stdlib = "org.jetbrains.kotlin:kotlin-stdlib:1.8.20"
junit-pioneer = "org.junit-pioneer:junit-pioneer:2.0.1"

ktor-client-auth = "io.ktor:ktor-client-auth:2.3.0"
ktor-client-cio = "io.ktor:ktor-client-cio:2.3.0"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.3.0"
ktor-client-core = "io.ktor:ktor-client-core:2.3.0"
ktor-client-logging = "io.ktor:ktor-client-logging:2.3.0"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.3.0"

ktorm-core = "org.ktorm:ktorm-core:3.6.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.6.0"
mockk = "io.mockk:mockk:1.13.5"
mockserver-client-java = "org.mock-server:mockserver-client-java-no-dependencies:5.15.0"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.33"
okhttp3-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.11.0"
rider-junit = "com.github.database-rider:rider-junit5:1.36.0"

ronin-test-data-generator = "com.projectronin.test:ronin-test-data-generator:0.0.2"
ronin-kafka = "com.projectronin:ronin-kafka:0.3.0"
snakeyaml = "org.yaml:snakeyaml:1.33"
spring-boot-autoconfigure = "org.springframework.boot:spring-boot-autoconfigure:2.7.8"
spring-vault-core = "org.springframework.vault:spring-vault-core:2.3.2"
testcontainers-mysql = "org.testcontainers:mysql:1.18.0"
woodstox-core = "com.fasterxml.woodstox:woodstox-core:6.5.1"
xerces = "xerces:xercesImpl:2.12.2"

[bundles]
test-mysql = ["mysql-connector-java", "testcontainers-mysql"]
jackson = ["jackson-annotations", "jackson-core", "jackson-databind", "jackson-dataformat-xml", "jackson-dataformat-yaml", "jackson-datatype-jsr310", "jackson-module-kotlin"]
ktor = ["ktor-client-auth", "ktor-client-cio", "ktor-client-content-negotiation", "ktor-client-core", "ktor-client-logging", "ktor-serialization-jackson"]
interop-kafka-events = [
    "interop-kafka-event-resource-publish",
    "interop-kafka-event-resource-load",
    "interop-kafka-event-resource-request"
]





